- .github/workflows/ci.yml
Runs CI when release tags are pushed.
> Run CI on release tag push

- README.md
This adds a "stay in touch" section to the readme with links to the Foxglove slack.
Fixes #7
> Add a "stay in touch" section to the readme

- examples/download.py
- examples/events.py
- foxglove_data_platform/client.py
- setup.cfg
- tests/test_client.py
This makes the `download_data` function more ergonomic.
Now it will just return the data directly instead of requiring the user to assemble the chunked responses. It now allows a `callback` parameter to monitor the progress of the download.
> Make download endpoint more ergonomic

- foxglove_data_platform/client.py
- setup.cfg
Fix missing `Protocol` type error by importing from `typing_extensions`.
> Fix typing_extensions bug

- Pipfile.lock
- foxglove_data_platform/client.py
- tests/test_client.py
This adds client calls for deleting events and for fetching single devices by id.
Fixes #22
Fixes #18
> Support deleting events and fetching individual devices

- foxglove_data_platform/client.py
- setup.cfg
- tests/api_url.py
- tests/test_client.py
- tests/test_data.py
- tests/test_devices.py
- tests/test_events.py
This adds a `delete_import` method for deleting existing imports and also breaks up the client test into resource-specific test files.
> Breakup tests and add delete import call

- setup.cfg
This updates the setup.cfg dependencies to include the `typing_extensions` library needed by Python 3.7.
Fixes #28
> Require typing_extensions library

- Pipfile.lock
- foxglove_data_platform/client.py
- setup.cfg
- tests/test_imports.py
Adds missing parameters to the `get_imports` call.
The API endpoint supports a number of optional parameters. This adds them to the client's `get_imports` method.
Fixes #31
> Add params to get_imports call

- foxglove_data_platform/client.py
- setup.cfg
- tests/test_client.py
Allows clients to pass snake_case names for the `sortBy` arg. This can be used in additional endpoints in the future.
Docs discussion: https://github.com/foxglove/website/pull/424#discussion_r844501114
> Camelize sortBy values in request

- foxglove_data_platform/client.py
- setup.cfg
Allows clients to filter imports by filename.
I documented the API changes on the site; it looks like we haven't documented python parameters there.
Resolves #45.
> Add filename filter to imports

- foxglove_data_platform/client.py
`Client` takes an optional `host=` constructor argument, to point it towards a different API service host.
Allow the user to point at a different API host, for testing against non-production instances of the API service.
> client: allow user to point at custom API host

- foxglove_data_platform/client.py
`bytes` is immutable, so the operation `data += chunk` creates a new object and copies the old data into it along with the new data. This is inefficient, and throttles download speed, especially after a significant number of bytes have already been downloaded. Anecdotally, I saw my download speed dip down to 800Kb/s before I went looking for this bug.
This PR replaces its usage with `BytesIO`, which is a mutable byte buffer with efficient appends via write(). After making this change I saw my download speed limited by my network bandwidth rather than CPU.
> client: speed up download_data using BytesIO

- foxglove_data_platform/client.py
- tests/test_events.py
- tests/test_imports.py
This provides more specific, user-friendly error messages in response to request errors on additional methods.
#25 added support for this, but it looks like we had a handful of overlapping PRs at that time, and some methods aren't yet making use of this.
Resolves #57.
> Display client error messages on more endpoints

- Pipfile
Set `install_search_all_sources = true` for pipenv, to match legacy behavior: https://pipenv.pypa.io/en/latest/advanced/#specifying-package-indexes.
`pipenv`, starting with `2022.3.23`, restricts each package to a single source for security reasons. This change to the default behavior broke CI installs. As far as I can tell, resolution for transitive dependencies uses the default source, rather than the source specified for the intermediate dependency. For example, `catkin` was no longer found (in pypi), even though it's imported via rosbag, which we specify with `index="ros"` ([example action](https://github.com/foxglove/py-data-platform/actions/runs/3855588765/jobs/6570797783)). 
Per the docs, it may be acceptable to continue to search all sources, as long as we're confident in our lock …
> Search all sources

- Pipfile.lock
- foxglove_data_platform/client.py
This adds support for sort & pagination on the call to `get_imports`. I added the new params to the end of the list. Note other methods like `get_events` don't have these at the end, so we're not consistent here, but this seems like something we can review in a future major release.
This also updates the checks when building the query parameters for various methods — including them only if not `None`, rather than stripping out other falsy values.
I'm not sure if there's a meaningful test I can add given what's there today. I'll open a corresponding website documentation PR.
> Support sort and pagination on data/imports

- foxglove_data_platform/client.py
- setup.cfg
- tests/test_devices.py
* deprecates `serial_number` argument in create_device.
> create_device: remove serial number argument

- foxglove_data_platform/client.py
- setup.cfg
This updates the return types for the following client calls, removing any fields that are not publicly documented:
- `get_device` (timestamps)
- `get_devices` (timestamps)
- `get_imports` (metadata)
This fixes an issue with the current API version where timestamps are not included in the response to `devices/{id}`.
This includes a version bump to 0.4.0.
> Remove undocumented fields from response objects

- examples/events.py
- foxglove_data_platform/client.py
- setup.cfg
- tests/test_events.py
* Callers are forced to use keyword arguments on all Client methods. This makes migration slightly easier for users when we make breaking API changes. This change itself is a breaking change compared to the current released version of the library.
* `get_events`, `create_event` and `delete_event` are updated to fit the `/v1/events` stable API.
> migrate to use v/1events, force keyword arguments on all client methods

- foxglove_data_platform/client.py
- setup.cfg
- tests/string_message_pb2.py
- tests/test_attachments.py
- tests/test_json_messages.py
- tests/test_recordings.py
Adds wrappers to list recordings, list attachments, download an attachment, and download a recording by ID.
> Add methods to list and download recordings and attachments

- foxglove_data_platform/client.py
This fixes the `id` param in the download_attachment docstring.
> Fix docstring param

- foxglove_data_platform/client.py
- setup.cfg
- tests/test_imports.py
This makes the `device_id` argument to `delete_import` optional.
The REST API no longer requires a device ID to be sent with deletion requests as the import IDs returned are unique. This brings the client method inline with those expectations. `device_id` is still a named kw argument to avoid breaking existing scripts.
Fixes #76.
> Ignore device ID in delete call

- foxglove_data_platform/client.py
- setup.cfg
- tests/test_data.py
- tests/test_events.py
Since we introduced optional device name, if it is not supplied it will be set to None and converted to null in the request, which the API will reject. Other methods are already performing this filtering.
> Filter None parameters in event creation and data upload

- .github/workflows/ci.yml
In #88, to resolve CI errors, I downgraded pipenv (first to 2022.12.19, then to 2023.6.18, which I had seen succeed in CI previously). Once merged to main, CI failed. The dependencies had been cached after successfully installing using the former version; the latter version doesn't work — confirmed in #90.
This should fix CI errors on main for now.
> Downgrade pipenv to 2022.12.19

- .github/workflows/ci.yml
In particular, if the source of a PR is a fork do not run the test build. Doing so causes this CI step to fail because the API token is missing.
This is the approach used in the mcap repo: https://github.com/foxglove/mcap/blob/a68c76979d646fa90a24bff3457be2da0c371f0a/.github/workflows/ci.yml#L259
> Skip build steps under some conditions

- setup.cfg
This skips 0.11.0. The version bump for that tag was skipped and the release job failed.
> Bump release version to 0.12.0

- Pipfile
- Pipfile.lock
This removes the rosbag dev dependency. We do not import this in any code. As a result, `certifi` is upgraded to 2023.7.22, which will resolve [dependabot alert #8](https://github.com/foxglove/py-data-platform/security/dependabot/8).
> Remove rosbag dependency

- foxglove_data_platform/client.py
- setup.cfg
- tests/test_stream_messages.py
Adds `iter_messages`, for streaming messages from data platform asynchronously.
This method not have the same yielded type as `get_messages`, because the get_messages API was determined before we had proper message iteration in the MCAP python library. 
In detail:
|        | get_messages | iter_messages |
|  --- |--------------- | --------------- |
| stream behavior | downloads entire stream first | yields the first element as soon as it is downloaded |
| element type | (topic, `mcap.Message`, decoded message) | (`mcap.Schema`, `mcap.Channel`, `mcap.Message`, decoded message) |
In my opinion the `get_messages` API unneccessarily hides information from the MCAP that the user might want (like channel metadata, topic schema content). It's still easy for them to pull the topic out of the …
> client: add method to stream messages asynchronously

- .github/workflows/ci.yml
None.
I've set up pypi to authorize GitHub Actions to push packages from this repo, following this guide: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-pypi
After this change, the PYPI_API_TOKEN (and TESTPYPI) github secrets are no longer  required and can be removed.
> ci.yml: PyPI uses oidc for auth

- foxglove_data_platform/client.py
Fix multiple calls to `get_messages` or `iter_messages` interfering with each other
The default decoder factories may be mutated by calls to `get_messages` or `iter_messages` (factories store internal state). Deep-copying them prevents consecutive calls to these functions affecting each other.
> Deep copy decoder factories

- setup.cfg
Releasing changes from https://github.com/foxglove/py-data-platform/pull/103 & #98
None
0.14.0 was never actually published. Bumping to 0.14.1 to try and fix CI.
> Bump version to 0.14.1

- foxglove_data_platform/client.py
- setup.cfg
The `foxglove-data-platform` package has been renamed to `foxglove-client`. Please migrate to `foxglove-client` to receive future updates.
https://github.com/foxglove/docs/pull/271
Also added logging of existing deprecations ~which will be removed in #105~ – decided not to do this for now, but we can still add the warnings.
> Add deprecation warning for impending rename

- foxglove/client.py
Use `mcap` as the default OutputFormat.
None
Support `mcap` and use it as the default OutputFormat. It functions the same as `mcap0`, which is being deprecated in favor of using `mcap`.
Fixes FG-9084
> use mcap as default OutputFormat

- .github/workflows/ci.yml
- examples/downloading_data.py
- examples/fetching_messages.py
None
None
This updates the "fetching_messages" example to remove a deprecated method call in favor of the streaming `iter_messages`. Instead of printing the length, it prints the timestamp, channel, and topic of each message; for example:
```txt
1616425609698483083 | /gps/navheading          | sensor_msgs/Imu
1616425609700292327 | /gps/fix_velocity        | geometry_msgs/TwistWithCovarianceStamped
```
> Update "fetching_messages" example

- .github/workflows/ci.yml
None
None
Our most recent publish step failed: https://github.com/foxglove/foxglove-python/actions/runs/13660769163/job/38191137604
We appear to need this fix: https://github.com/pypa/gh-action-pypi-publish/pull/340 ...which is in [unstable/v1](https://github.com/pypa/gh-action-pypi-publish/commits/unstable/v1) but not yet in a versioned release.
> Use unstable publish action

- setup.cfg
None.
None
This is a re-release for the recording `key` change in 0.15.4, after a failed publish action (#118).
> Bump version to 0.15.5

- .github/workflows/ci.yml
None
None
This skips attestations when publishing to Test PyPI. Otherwise, with recent versions of the action, there will be conflicting attestations when we publish to [production] PyPI.
The underscore-dash changes match the documentation, but are normalized away in the action.
> Skip test attestations

- setup.cfg
None.
None
Re-release hopefully not subject to the duplicate attestations error (#120).
> Bump version to 0.15.6

- foxglove/client.py
Deprecates `get_imports`. Use `get_recordings` with `import_status: "complete"` instead.
None
Deprecates `get_imports`, matching the API deprecation. This functionality and more is supported by `get_recordings`. See https://docs.foxglove.dev/api#tag/Recordings/paths/~1recordings/get for more info.
> deprecate get_imports

- foxglove/client.py
- tests/test_devices.py
Handle missing projectId in get_device response
None
Gracefully handle a missing Project ID in device methods. The `projectId` field is optional on the API response that these methods call.
> handle missing projectId in get_device response
